Cosmetic/Cosmetic/Models/YeuThich.cs
using System;
using System.Collections.Generic;

namespace Cosmetic.Models
{
    public partial class YeuThich
    {
        public int MaYt { get; set; }
        public int? MaSp { get; set; }
        public string MaKh { get; set; }
        public DateTime? NgayChon { get; set; }
        public string MoTa { get; set; }
        public KhachHang MaKhNavigation { get; set; }
        public SanPham MaSpNavigation { get; set; }
    }
}

Cosmetic/Cosmetic/Controllers/YeuThichController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Cosmetic.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Cosmetic.Controllers
{
    public class YeuThichController : Controller
    {
        private readonly MyPhamContext _context;

        public YeuThichController(MyPhamContext context)
        {
            _context = context;
        }

        // GET: YeuThich
        public async Task<IActionResult> Index()
        {
            var myPhamContext = _context.YeuThich.Include(y => y.MaKhNavigation).Include(y => y.MaSpNavigation);
            return View(await myPhamContext.ToListAsync());
        }


        [Route("[controller]/[action]")]
        public IActionResult themYT(int masp, string makh)
        {
            ViewBag.chon = "1";
            YeuThich yt = new YeuThich
            {
                MaKh = makh,
                MaSp = masp,
                NgayChon = DateTime.Now,

            };

            _context.YeuThich.Add(yt);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [Route("[controller]/[action]")]
        public IActionResult boYT(int masp)
        {
            YeuThich yt = _context.YeuThich.SingleOrDefault(p => p.MaSp == masp);

            _context.YeuThich.Remove(yt);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Cosmetic/Cosmetic/Views/YeuThich/Index.cshtml
@model IEnumerable<Cosmetic.Models.YeuThich>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Frontend.cshtml";
}
<div id="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- breadcrumb-->
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                        <li aria-current="page" class="breadcrumb-item active">Sản phẩm yêu thích</li>
                    </ol>
                </nav>
            </div>
            <div class="col-lg-3">
                <!--
                *** CUSTOMER MENU ***
                _________________________________________________________
                -->
                <div class="card sidebar-menu">
                    <div class="card-header">
                        <h3 class="h4 card-title">Khách Hàng</h3>
                    </div>
                    <div class="card-body">
                        <ul class="nav nav-pills flex-column"><a asp-action="Index" asp-controller="HoaDon" class="nav-link"><i class="fa fa-list"></i>Hóa đơn của bạn</a><a asp-action="Index" asp-controller="YeuThich" class="nav-link active"><i class="fa fa-heart"></i> Sản phẩm yêu thích</a><a asp-action="Index" asp-controller="KhachHang" class="nav-link"><i class="fa fa-user"></i>Tài khoản</a><a asp-action="DangXuat" asp-controller="DangNhap" class="nav-link"><i class="fa fa-sign-out"></i> Đăng xuất</a></ul>
                    </div>
                </div>
                <!-- /.col-lg-3-->
                <!-- *** CUSTOMER MENU END ***-->
            </div>
            <div id="wishlist" class="col-lg-9">
                <div class="box">
                    <h1>Sản phẩm yêu thích</h1>
                </div>
                @if (Context.Session.Get<KhachHang>("TaiKhoan") != null)
                {
                    MyPhamContext db1 = new MyPhamContext();
                    KhachHang kh = Context.Session.Get<KhachHang>("TaiKhoan");

                    var ds = db1.YeuThich.Where(p => p.MaKh == kh.MaKh).ToList();
                    <div class="row products">

                        @foreach (var item1 in ds)
                        {
                            SanPham sp = db1.SanPham.Find(item1.MaSp);
                            <div class="col-lg-4 col-md-6">
                                <div class="product">
                                    <div class="flip-container">
                                        <div class="flipper">
                                            <div class="front"><a href="detail.html"><img src="~/Hinh/beauty/@sp.Hinh" alt="" class="img-fluid"></a></div>
                                            <div class="back"><a href="detail.html"><img src="~/Hinh/beauty/@sp.Hinh2" alt="" class="img-fluid"></a></div>
                                        </div>
                                    </div><a href="detail.html" class="invisible"><img src="~/Hinh/beauty/@sp.Hinh" alt="" class="img-fluid"></a>
                                    <div class="text">
                                        <h3><a asp-action="ChiTiet" asp-controller="SanPham" asp-route-id="@sp.MaSp">@sp.TenSp</a></h3>
                                        <p class="price">
                                            <del>@sp.GiaCu.Value.ToString("#,##0") đ </del> @sp.DonGia.Value.ToString("#,##0") đ
                                        </p>
                                        <p class="buttons"><a asp-action="ChiTiet" asp-controller="SanPham" asp-route-id="@sp.MaSp" class="btn btn-outline-secondary">Chi tiết</a><a asp-action="AddToCart" asp-controller="GioHang" asp-route-mahh="@sp.MaSp" asp-route-sl="1" class="btn btn-primary"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ</a></p>
                                    </div>
                                    <!-- /.text-->
                                </div>
                                <!-- /.product            -->
                            </div>

                        }

                        <!-- /.products-->
                    </div>
                }
                else
                {
                    <div class="alert alert-danger" style="text-align:center"> <a asp-action="DangNhap" asp-controller="DangNhap">Bạn cần đăng nhập để xem sản phẩm yêu thích </a></div>
                }
            </div>
        </div>
    </div>