Cosmetic/Cosmetic/Models/RestoreAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cosmetic.Models
{
    public class RestoreAccount
    {
        public string UserEmail { set; get; }
    }
}

Cosmetic/Cosmetic/Controllers/RestoreAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cosmetic.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;
using Cosmetic.Encrytions;
using System.Text;
using System.Net.Mail;

namespace Cosmetic.Controllers
{
    public class RestoreAccountController : Controller
    {
        private readonly MyPhamContext db;
        PasswordHasher pH = new PasswordHasher();
        public RestoreAccountController(MyPhamContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public string CreatePassword(int length)
        {
            const string valid = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
            StringBuilder res = new StringBuilder();
            Random rnd = new Random();
            while (0 < length--)
            {
                res.Append(valid[rnd.Next(valid.Length)]);
            }
            return res.ToString();
        }
        [Route("[controller]/[action]")]
        public IActionResult Forget(RestoreAccount model)
        {
            if (ModelState.IsValid)
            {
                KhachHang kh = db.KhachHang.SingleOrDefault(p => p.Email == model.UserEmail);
                if (kh == null)
                {
                    ModelState.AddModelError("Lỗi", "Người dùng không tồn tại");
                    return View("Index");
                }
                else
                {
                    string mk = CreatePassword(12);
                    kh.MatKhau = pH.HashPassword(mk);
                    db.Update(kh);
                    db.SaveChangesAsync();
                    MailMessage mm = new MailMessage("eshoppingmanager@gmail.com", model.UserEmail);
                    mm.Subject = "Mật khẩu tài khoản Eshop";
                    mm.Body = string.Format("Xin chào: <h1>{0}</h1> <br/> Mật khẩu mới của bạn là <h1>{1}</h1>", kh.HoTen, mk);
                    mm.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.EnableSsl = true;
                    smtp.Credentials = new System.Net.NetworkCredential("eshoppingmanager@gmail.com", "EShop@21298");
                    smtp.Send(mm);
                    TempData["Success"] = "Xin hãy kiểm tra Email của bạn!";
                    return View("Index");
                }
            }
            return View("Index");
        }
    }
}

Cosmetic/Cosmetic/Views/RestoreAccount/Index.cshtml
@model Cosmetic.Models.RestoreAccount
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Frontend.cshtml";
}

<div id="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- breadcrumb-->
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                        <li aria-current="page" class="breadcrumb-item active">Tìm lại mật khẩu</li>
                    </ol>
                </nav>
            </div>

            <div class="col-lg-9" style="width:800px; margin:0 auto;">
                <div class="box">
                    @if (TempData["Success"] != null)
                    {
                        <div class="text-success">
                            <p><strong>Thành công!</strong> @TempData["Success"].ToString()</p>
                        </div>
                    }
                    <h1 style="text-align:center">Reset password </h1>
                    <p class="text-muted">Vui lòng nhập địa chỉ email vào ô bên dưới. Bạn sẽ nhận được một mật khẩu ngẫu nhiên để đăng nhập vào tài khoản.</p>
                    <form method="post" asp-controller="RestoreAccount" asp-action="Forget">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <input asp-for="UserEmail" type="email" placeholder="Địa chỉ email" class="form-control" required>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-mail-forward"></i>Gửi đi</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>